[project]
authors = ["Mitchell R. Vollger <mvollger@gmai.com>"]
channels = ["conda-forge", "bioconda"]
description = "Add a short description here"
name = "fire-figures"
platforms = ["linux-64"]
version = "0.1.0"


[dependencies]
r-base = ">=4.1"
r-tidyverse = { version = ">=2.0", channel = "conda-forge" }
r-rcolorbrewer = { channel = "conda-forge" }
r-scales = { channel = "conda-forge" }
"r-data.table" = "*"
r-ggrepel = "*"
r-cowplot = "*"
r-argparse = "*"
r-glue = "*"
r-ggnewscale = "*"
r-valr = "*"
r-ggforce = "*"
r-xlsx = { channel = "conda-forge" }
"r-r.utils" = { channel = "conda-forge" }
r-ggpubr = "*"
r-ggextra = "*"
r-ggridges = "*"
r-ggside = "*"
r-ggh4x = "*"
radian = "*"
r-languageserver = "*"
htslib = "*"
bcftools = "*"
samtools = ">=1.15"
bedtools = "*"
r-reticulate = ">=1.38.0,<2"
r-ggbeeswarm = ">=0.7.2,<0.8"
r-hexbin = ">=1.28.5,<2"
